### PR TITLE
Feature/socket minimum tls version

### PR DESCRIPTION
**Pull request by ocZio**
Still WIP.

### CODE REVIEW

**Comment by ocZio** [comment]
https://travis-ci.org/quickfixgo/quickfix/jobs/203805095#L1449-L1464

**Comment by cbusbey** [comment]
Checked out locally and confirmed it fails outside of travis.  You should revisit your logic in loadTLSConfig for those test cases.

**Comment by ocZio** [comment]
@cbusbey Thanks, will checkout it out locally and see why it fails. One thing which triggered my curiosity was the error 0x303 != 771, how is this possible ? :)

**Comment by ocZio** [comment]
Ready for Review/Merge.

**Comment by ocZio** [comment]
bump :)

**Comment by cbusbey** [comment]
🍻

**Pull request merged**
