### PR TITLE
added support for code generation on windows

### PR DESCRIPTION
**Pull request by abheyshah**
Minor changes that permit code generation on windows and uses filepath in place of path. An initial prototype test function has been added but doesn't really do any validation and really needs a cross platform implementation.

### CODE REVIEW

**Comment by cbusbey** [comment]
This should be unnecessary if your GOPATH is correctly set up.  For details on GOPATH

https://github.com/golang/go/wiki/GOPATH

**Comment by abheyshah** [comment]
Hi, My GOPATH is (correctly) set. Apologies if the code I submitted implied
that was the main issue. The real issue is that windows uses backslashes as
file separator. So the generated imports are like this   "github.com
\quickfixgo/tag".
And \q is an unknown escape sequence. Appreciate you may not have immediate
access to a windows machine to verify the issue and integrate the commit,
but perhaps keep it as an open issue?



Using your original code I get:

C:\Users\Abhey\Go\src\github.com\quickfixgo>set GO
GOPATH=C:\Users\Abhey\Go
GOROOT=C:\Go\

C:\Users\Abhey\Go\src\github.com\quickfixgo>generate-fix
quickfix\spec\FIX50.xml
Error parsing fix50/tradingsessionlistrequest/TradingSessionListRequest.generated.go:
8:14: unknown escape sequence (and 3 more errors)
Error parsing fix50/liststatusrequest/ListStatusRequest.generated.go: 8:14:
unknown escape sequence (and 2 more errors)
Error parsing fix50/tradingsessionstatusrequest/TradingSessionStatusRequest.generated.go:
8:14: unknown escape sequence (and 3 more errors)
...
C:\Users\Abhey\Go\src\github.com\quickfixgo>type
fix50\tradingsessionlistrequest\TradingSessionListRequest.generated.go
package tradingsessionlistrequest

import (
        "github.com\quickfixgo/tag"
        "github.com/quickfixgo/quickfix"
)

//TradingSessionListRequest is the fix50 TradingSessionListRequest type,
MsgType = BI
type TradingSessionListRequest struct {
...

**Comment by Moataz-E** [comment]
I can confirm that I am facing the same issue on a windows machine.  Trying abheyshah's version fixed the issue for me.

Previously, my generated FIX was throwing a lot of errors and looked like this:

```
import (
	"C:\Users\<my username>\work\code\go\src\github.com\quickfixgo\quickfix/tag"
	"github.com/quickfixgo/quickfix"
)
```

**Comment by cbusbey** [comment]
@Moataz-E I think you hit on a more elegant solution

**Comment by cbusbey** [comment]
handled by #323

**Pull request closed without merging**
